site_name: Imaginaires Sans Frontières
site_description: Imaginaires Sans Frontières contribue au bien être des patients par des parenthèses ludiques.
site_url: https://imaginaires.github.io/
theme:
  language: fr
  name: material
  logo: img/logo-isf.svg
  favicon: img/favicon.ico
  font:
    text: Glory
    code: Source Code Pro
  palette:
    scheme: default
    primary: purple
    accent: teal
  features:
    - navigation.tabs
    - navigation.indexes
logo: assets/images/logo-isf.svg
plugins:
  - search
  - blog
extra:
  social:
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/imaginairessansfrontieres
copyright: Copyright &copy; 2024 Imaginaires Sans Frontières
nav:
  - Acceuil: index.md
  - Blog:
     - blog/index.md

