site_name: Imaginaires Sans Frontières
site_description: Imaginaires Sans Frontières est une association dont la mission est de contribuer au bien être des patients par des parenthèses ludiques.
site_url: https://imaginaires.github.io/
theme:
  language: fr
  name: material
  logo: img/logo-isf.svg
  favicon: img/favicon.ico
  font:
    text: Glory
    code: Source Code Pro
  palette:
    scheme: default
    primary: purple
    accent: teal
  features:
    - navigation.indexes
    # - navigation.tabs
plugins:
  - search
  - blog
extra:
  social:
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/imaginairessansfrontieres
  generator: false
hooks:
  - hooks/socialmedia.py
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - À Propos: index.md
  - Blog:
     - blog/index.md
copyright: Copyright &copy; 2024 Imaginaires Sans Frontières
