authors:
  bm:
    name: Baptiste
    description: Alchimiste des Rêves
    avatar: https://cdn.iconscout.com/icon/premium/png-256-thumb/dreaming-1589230-1345262.png
  mt:
    name: Mickael
    description: Artisan des Quêtes
    avatar: https://cdn-icons-png.flaticon.com/512/1408/1408801.png

