authors:
  bm:
    name: Baptiste
    description: Random
    avatar: https://avatars.githubusercontent.com/u/932156
    url: https://github.com/squidfunk
  mt:
    name: Mickael
    description: Random 2
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/mickaeltemporao
